# Generated by Django 5.2.5 on 2025-08-19 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("category", "name")},
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="contact",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(default=" DEFAULT123", max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="inventory.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
